#! /bin/bash
java_version=11
cassandra_version=41x

sudo apt-get update
sudo apt-get install -y openjdk-${java_version}-jre

# Install cassandra
echo "deb https://debian.cassandra.apache.org ${cassandra_version} main" | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list
deb https://debian.cassandra.apache.org ${cassandra_version} main
curl https://downloads.apache.org/cassandra/KEYS | sudo apt-key add 
sudo apt-get update
sudo apt-get install -y cassandra